---
- name: Generate the RSA keys
  command: openssl genrsa -out {{ item }}.key {{ openvpn_key_size }}
  args:
    chdir: "{{ openvpn_path }}"
    creates: "{{ item }}.key"
  with_items:
    - ca
    - server

- name: Create directories for clients profile
  file:
    path: "{{ openvpn_path}}/{{ item }}"
    state: directory
  with_items: "{{ openvpn_clients }}"

- name: Generate RSA keys for the Clients
  command: openssl genrsa -out {{ item }}.key {{ openvpn_key_size }}
  args:
    chdir: "{{ openvpn_path }}/{{ item }}"
    creates: "{{ item }}.key"
  with_items: "{{ openvpn_clients }}"

- name: Set the proper permissions on all RSA keys
  file:
    path: "{{ openvpn_path }}"
    owner: root
    group: root
    mode: 0600
    state: directory
    recurse: yes

- name: Generate CA certificate Authority 
  command: openssl req -nodes -batch -new -x509 -key {{ openvpn_ca }}.key -out {{ openvpn_ca }}.crt
            -days {{ openvpn_days_valid }} -subj "{{ openssl_request_subject }}/CN=ca-certificate"
  args:
    creates: "{{ openvpn_ca }}.crt"

- name: Generate OpenSSL configuration that will be used for the Server certificate req and ca commands
  template:
    src: openssl-server-certificate.cnf.j2
    dest: "{{ openvpn_path }}/openssl-server-certificate.cnf"

- name: Check that the "index.txt" file exist
  stat:
    path: "{{ openvpn_path }}/index.txt"
  register: index_exist

- name: Create blank database file that will be used when generating the Server certificate
  file:
    path: "{{ openvpn_path }}/index.txt"
    state: touch
  when: index_exist.stat.exists == False

- name: Check that the "serial" file exist
  stat:
    path: "{{ openvpn_path }}/serial"
  register: stat_result

- name: Copy/Create the serial file that will be used when generating the Server certificate
  copy:
    content: "01"
    dest: "{{ openvpn_path }}/serial"
  when: stat_result.stat.exists == False

- name: Generate the CSR for the Server
  command: openssl req -batch -extensions server -new -key server.key -out server.csr -config {{ openvpn_path }}/openssl-server-certificate.cnf
  args:
    chdir: "{{ openvpn_path }}"
    creates: server.csr

- name: Generate the Certificate for the Server
  command: openssl ca -batch -extensions server -in server.csr -out server.crt -config openssl-server-certificate.cnf
  args:
    chdir: "{{ openvpn_path }}"
    creates: server.crt

- name: Generate CSRs for the clients
  command: openssl req -new -key {{ item }}.key -out {{ item }}.csr -subj "{{ openssl_request_subject }}/CN={{ item }}"
  args:
    chdir: "{{ openvpn_path }}/{{ item }}"
    creates: "{{ item }}.csr"
  with_items: "{{ openvpn_clients }}"

- name: Generate certificates for the clients
  command: openssl x509 -CA {{ openvpn_ca }}.crt -CAkey {{ openvpn_ca }}.key -CAcreateserial -req -days {{ openvpn_days_valid }} -in {{ item }}.csr -out {{ item }}.crt
  args:
    creates: "{{ item }}.crt"
    chdir: "{{ openvpn_path }}/{{ item }}"
  with_items: "{{ openvpn_clients }}"

- name: Generate the HMAC firewall key
  command: openvpn --genkey --secret {{ openvpn_hmac_firewall }}
  args:
    creates: "{{ openvpn_hmac_firewall }}"

- name: Register CA certificate contents
  command: cat ca.crt
  args:
    chdir: "{{ openvpn_path }}"
  register: openvpn_ca_contents

- name: Register client certificate contents
  command: cat {{ item }}.crt
  args:
    chdir: "{{ openvpn_path }}/{{ item }}"
  with_items: "{{ openvpn_clients }}"
  register: openvpn_client_certificates

- name: Register client key contents
  command: cat {{ item }}.key
  args:
    chdir: "{{ openvpn_path }}/{{ item }}"
  with_items: "{{ openvpn_clients }}"
  register: openvpn_client_keys

- name: Register HMAC firewall contents
  command: cat ta.key
  args:
    chdir: "{{ openvpn_path }}"
  register: openvpn_hmac_firewall_contents

- name: Create the client configs
  template:
    src: client.cnf.j2
    dest: "{{ openvpn_path }}/{{ item[0] }}/{{ openvpn_server }}.ovpn"
  no_log: yes
  with_together:
    - "{{ openvpn_clients }}"
    - "{{ openvpn_client_certificates.results }}"
    - "{{ openvpn_client_keys.results }}"

- name: Generate Diffie-Hellman parameters (this will take a while)
  command: openssl dhparam -out {{ openvpn_dhparam }} {{ openvpn_key_size }} -dsaparam
  args:
    creates: "{{ openvpn_dhparam }}"

- name: Retrieve the files that clients will need in order to connect to the OpenVPN server
  fetch:
    src: "{{ openvpn_path }}/{{ item }}/{{ openvpn_server }}.ovpn"
    dest: clients/{{ item }}.ovpn
    flat: yes
  no_log: yes
  with_items: "{{ openvpn_clients }}"
